### ISSUE TITLE
Error 126 when attempting to launch version 2.1.2

### ISSUE THREAD

**Issue by KemikalElite** [lx-s/WinMute#17]
WinMute version:
2.1.2
Windows version:
Win 10 Pro 64 21H2 19044.1889

Hello again,
After installing the latest version of WinMute and launching it, it shows "LoadLibrary failed with error 126: The module could not be found"

I've tried uninstalling and reinstalling (ensuring the install folder and registry path are empty), rebooting the computer, running SFC scannow, installing as a user app and a system app, also tried running the portable zip.

I also received this error on a different PC which has never had WinMute installed before.

If I install the old version 2.1.1, it works normally without the error.

Most of the topics and videos covering this error code show its often related to an AMD graphics driver, however I do not have an AMD graphics card.

**Comment by lx-s** [comment]
Oh my… sorry for that!
I must have supplied the wrong DLL with the setup.
For now you could download the zip file and overwrite the 2.1.1 WinMute.exe with the 2.1.2 version of the release zip.

I must have screwed up the setup. Sorry for all your troubles :(

**Comment by lx-s** [comment]
I updated the release: https://github.com/lx-s/WinMute/releases/tag/2.1.2.0
The problem was caused, because one of the DLL files (ScreensaverNotify) was still built as debug. Since you don't have the visual studio debug-libraries installed, windows couldn't load the DLL file (since dependencies where missing), which lead to that error message. Since I have those files installed, I didn't notice the problem.

I just re-uploaded the files.

Thanks for your report!
