### ISSUE TITLE
Problems with Overwatch 2

### ISSUE THREAD

**Issue by AlexWayfer** [lx-s/WinMute#18]
![image](https://user-images.githubusercontent.com/6510020/195830546-3e99f08c-5c7b-4fa2-985c-a3231c63dc49.png)

**Comment by AlexWayfer** [comment]
It was with old version, 1.9.9.1, let me check with the new one.

**Comment by lx-s** [comment]
To remove/replace ScreensaverNotify.exe you might have to restart, as, unfortunately, there is no way to tell Windows to unload it :(

**Comment by AlexWayfer** [comment]
Rebooted, the newest version installed (recommended user-specific way), the same error.

![image](https://user-images.githubusercontent.com/6510020/195982109-14ed0cfc-e794-41f5-aad4-62aba5874da2.png)

**Comment by lx-s** [comment]
I'll install overwatch and see if I can reproduce this error. Sorry for the inconvenience :|

**Comment by lx-s** [comment]
Today I've also noticed that Warhammer 40k DarkTide's "Anti Cheat" also flags the screensaver detection dll as "untrusted".

The reason for this might be, that I have no code signing certificate (and because of the high cost involved, I also don't plan on getting one).

I think the best way forward might be to actually drop screensaver detection, as the mechanism for this is also really flaky (having to load my own DLL into every process to actually get notified). This would also fix the problem, that it's impossible to delete WinMute's *.dll files until after a restart and only if WinMute has not been started...

I think in times of saving electricity and flat screens, screensavers aren't that widely used any longer.

**Comment by lx-s** [comment]
Removed the screensaver detection with the new release 2.2.0.
