### ISSUE TITLE
Mute on screen saver

### ISSUE THREAD

**Issue by cableghost** [lx-s/WinMute#34]
**Describe the solution you'd like**
Option to mute on screen saver.

**Comment by lx-s** [comment]
Hey there,

unfortunately this is a "won't fix". WinMute before 2.2.0 (s. Release-Note https://github.com/lx-s/WinMute/releases/tag/2.2.0) had the ability to Mute on Screensaver. Alas screensaver detection is extremely flaky on Windows as only the current active program gets notified when the screen saver starts, and the notification that the screensaver has ended does not always fire.

Also the implementation needs WinMute to inject its own code into every program so that it can try to get's the message regardless of what is the current active program. Since the code that gets injected has to have the correct bitness (32-bit, vs. 64-bit) I also had to provide a proxy program to handle both cases. This combined with the not so robust notifications from Windows led me to drop the feature.
Also nowadays most users just let their screen go to standby.

So if you really want to use the feature, you can still download WinMute <2.2.0 and mute on screensaver activation.

Sorry If can't give you better news.
