### ISSUE TITLE
Mute all output devices

### ISSUE THREAD

**Issue by notsupported** [lx-s/WinMute#5]
It seems WinMute only mutes the master volume of the primary output device. Would it be possible to extend this to all output devices?

I use my laptop's speakers as primary output. When I lock the device, WinMute correctly mutes this output. However, my headset still rings when a Skype or Teams call comes in. It's a Plantronics USB headset and it shows up as a different device in Windows. It is used only for calls.

**Comment by lx-s** [comment]
Thanks for your suggestion!

I will add this to the next update after 1.6. For this to work, I have to rework my "was already muted by the user"-detection (which is getting quite complicated in light of #4), and rework the audio device detection.

It will be a while when I come around to adding it, but I will (I have also multiple endpoints on my PC, so it will be easy to test :) )

**Comment by winedog** [comment]
Would this issue explain why WinMute is not working for me on a laptop that uses thunderbolt dock?  It works great on my desktop PC at home, but a laptop that I keep docked at work doesn't seem to work at all.  I can activate it and even manually mute the system, but as soon as a Skype call or Slack notification comes through the system unmutes?  I did set the Thunderbolt dock as the default audio device and it didn't seem to have any effect.

**Comment by lx-s** [comment]
> I can activate it and even manually mute the system, but as soon as a Skype call or Slack notification comes through the system unmutes?

I think those apps may unmute your system when they receive an incoming call.

For skype, you can configure this behaviour in [`Settings > Audio and Video > Unmute for incoming calls`](https://support.skype.com/en/faq/FA34863/how-do-i-change-audio-and-video-settings-in-skype-on-desktop).

I wonder if this setting is enabled in your skype installation.

**Comment by winedog** [comment]
I never noticed that setting before! It was turned on and that would explain why I saw it unmuting even when the system was unlocked and I would manually mute via WinMute.  I disabled it and Skype would no longer unMute while unlocked.

However, when I lock the system, an incoming Skype call would still ring.  

So I tried some testing and disabled the setting "Restore volume when returning" to see if the issue was that Winmute was simply not triggering the mute.  I locked the screen and then unlocked and it was still unmuted.

Then I exited and relaunched WinMute, Locked and Unlocked and the system remained muted.  If re-enable "Restore volume when returning", it doesn't work on the next screen Lock unless I quite/restart WinMute.  I replicated this behavior on both my laptop and desktop system.  

Is there an issue where Winmute has to be closed and relaunched after a settings change?

**Comment by lx-s** [comment]
That sounds... strange. I will try to recreate it

Sorry for not being very responsive right now. A month ago I started a new job which keeps me really busy.
I want to make a bigger revision of WinMute soon™, that includes some of the requests that have been written here, as well as log file option to (hopefully) better understand whats going on in some cases.

**Comment by lx-s** [comment]
Muting all endpoints is now available with WinMute 1.9.9 (This is a pre-release version for 2.0).
If you want, you can try it here: https://github.com/lx-s/WinMute/releases/tag/1.9.9
