### ISSUE TITLE
Mute when connected to particular wifi

### ISSUE THREAD

**Issue by Hx2-code** [lx-s/WinMute#6]
This will help mute Windiws when we are in  metro or resturant.

**Comment by lx-s** [comment]
This is a pretty specific problem, which would also require some UI work.

There would also be a significant delay until your Windows device is connected to the WiFi where you would have no "mute protection".

Maybe your use case is already covered by setting mute on hibernate or sleep?

Otherwise how about a global hotkey, to mute your PC/laptop? Pressing that would probably be faster
than waiting for the WiFi to be connected :)

**Comment by Hx2-code** [comment]
Actually sometimes its possible that we forget to toggle the hotkey. So even if there is a little delay auto mute will be useful.

**Comment by lx-s** [comment]
I'll see what I can do, but it'll take a while unfortunately :/

**Comment by Hx2-code** [comment]
Yes, take your time there is no hurry.

**Comment by lx-s** [comment]
You might be interested in this pre-release version: https://github.com/lx-s/WinMute/releases/tag/1.9.9.3 :)
![settings_wlan](https://user-images.githubusercontent.com/411211/163336519-d0e602c6-ea70-452e-a917-b9db1c02f958.png)
