### ISSUE TITLE
[request] stop any sound playing instead of mute

### ISSUE THREAD

**Issue by makedir** [lx-s/WinMute#7]
Not sure if this would be possible, but could you maybe implement an option to turn on, that instead of mute any audio source will be stopped?

Windows has global hotkey for media play/pause I think, at least you can do this with AutoHotkey with "^!Down::Send   {Media_Stop}"

**Comment by lx-s** [comment]
You mean, pause whatever is currently registered with Windows as "Playing" and showing in this popup
![grafik](https://user-images.githubusercontent.com/411211/133198038-5d7e6f22-be3c-46ff-b6b2-7a0e301ff941.png)
?

I can look into it!

**Comment by lx-s** [comment]
I looked at this issue but there are several problems.
- The MediaPlayback API is not easily accessible from a simple desktop app
- It is intended for your own playback to be controlled and not to control other apps
- WinMute could fake the hardware button for PLAY/PAUSE found on most keyboards, but it's not possible to send this key when the PC is locked. Also it's not possible to get the playback status beforehand, so if your media player is paused, it could result in playback being started when a mute condition triggers.

Because of all that, I have to close this issue with "can't fix" for now. Sorry :|
